name: freegrid_env
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - vispy==0.5.3
    - python-osc
    - openvr==1.3.2201 
    - pyquaternion
    - sounddevice
    - PyQt5
    - matplotlib
    - scipy

