name: Guided_HRTFs_env
channels:
  - defaults
dependencies:
  - python=3.6
  - pyqt
  - pyopengl
  - matplotlib
  - pyaudio
  - pip:
    - vispy==0.5.3
    - pyshtools
    - python-osc
    - sound-field-analysis
    - openvr
    - pyquaternion
    - sounddevice
    - pyfftw
    - soundfile

