name: Guided_HRTFs_env
channels:
  - defaults
dependencies:
  - python=3.6
  - pyqt
  - pyopengl
  - matplotlib
  - pip:
    - vispy==0.5.3
    - python-osc
    - sound-field-analysis
    - openvr==1.3.2201 
    - pyquaternion
    - sounddevice

